services:
  backend:
    build:
      context: .
    environment:
      - DATABASE_URL=postgres://postgres:shadow12#@db/postgres
    networks:
      - client-side
      - server-side
    ports:
      - 8088:8083
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=shadow12#
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - /home/postgresql/data:/var/lib/postgresql/data
networks:
  client-side: {}
  server-side: {}
volumes:
  backend-cache: {}
  db-data: {}
