# https://www.codementor.io/@adammertz/basic-tutorial-using-docker-and-python-1gxmzm43k2
From shadowzeng/rust-1.52.1-slim

RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*
